### PR TITLE
Enable Style/Lambda cop

### PR DESCRIPTION
**Pull request by will-in-wi**
For discussion.

Followup to https://github.com/capistrano/capistrano/pull/1594

### CODE REVIEW

**Comment by mattbrictson** [comment]
No problem with this one. :+1:

**Comment by mattbrictson** [comment]
@will-in-wi Can you fix this the conflicts in this and the other remaining RuboCop PRs?

You should rebase on top of master because it has an important fix for Rake 11.0 that prevents Travis builds from failing.

**Comment by will-in-wi** [comment]
All of the PRs have been rebased on master.

Thanks!

**Comment by mattbrictson** [comment]
@will-in-wi Another conflict.

**Pull request merged**
