### PR TITLE
Increase Carbon ad revenue by 30%

### PR DESCRIPTION
**Pull request by bvallelunga**
Hey @capistrano,

Awesome choice picking Carbon ads, they are simple and unobtrusive! My friend and I have been working on our spare time a way to increase Carbon revenue by ~30%. 

We realized that ad blockers were taking a huge chunk of our revenue so we built [Miza](https://miza.io). You can think of Miza as a bodyguard for your ads, when Miza is installed, your ads will always appear.

We are currently in a private beta and think you would be a great fit! If you want to give us a try, it's as simple as merging the pull request. Once you have merged the pull request you can view your analytics with this link: [http://localhost:3030/invite/dhifn](http://localhost:3030/invite/dhifn)

You can contact me directly if you have any questions at brian@miza.io Thanks for your time!

### CODE REVIEW

**Comment by leehambley** [comment]
Hi @bvallelunga I'll let the other mainteiners weigh-in, but I'm pro-choice, and I respect people's right to install an ad blocker. I also have a cordial relationship with the people at CarbonAds who have always served us well. 

Note also please that your link to preview, to `localhost` can only work for you!

**Comment by will-in-wi** [comment]
I second @leehambley's stated opinion. I'd rather have ads be blockable.

**Comment by leehambley** [comment]
We are three maintainers, and we have consensus! Thanks for the PR @bvallelunga but we won't be integrating Miza.

**Comment by bvallelunga** [comment]
Sure! Thank you for your time.

**Pull request closed without merging**
