### PR TITLE
Update style for alert messages at documentation pages

### PR DESCRIPTION
**Pull request by harrykiselev**
### Summary

This PR is attempt to fix alert messages style at capistrano documentation.

### Other Information

Hello!

At first I found forgotten class (.alert-box) at alert message on [Installation page](http://capistranorb.com/documentation/getting-started/installation/).

This page looked like:

After I added this class, alert message began to look like this (as all alert messages at documentation):

It looks like alerts lost their line-height property (compared with paragraphs of text on same page).

To fix this I did not touch documentation stylesheets (.alert-box class styles). I took advantage of the fact that «p» tags has this property and have changed tag for all alerts from «div» to «p».

After that alert messages began looks like this (before and after update versions):

It touched some list of pages:

* [Installation](http://capistranorb.com/documentation/getting-started/installation/)
* [Preparing Your Application](http://capistranorb.com/documentation/getting-started/preparing-your-application/)
* [How can I set Capistrano configuration paths?](http://capistranorb.com/documentation/faq/how-can-i-set-capistrano-configuration-paths/)

It seems to me that the styles of alert messages look more pleasant.

Thanks :)

### CODE REVIEW

**Comment by mattbrictson** [comment]
Hi, thanks for taking the time to improve the styles!

It looks like the `.alert-box` has not been styled for a long time, so I don't know what the original intent was for the visual effect.

I think the style you've added in this PR makes the alerts a bit hard to read, in particular the blue and white text on the solid red background. Could you change it to something a bit more subtle? For example, I like how the [Rails Guides](http://guides.rubyonrails.org/getting_started.html) use a yellow box that calls attention to the text without being overbearing.

screen shot 2017-02-14 at 6 54 15 pm

**Comment by harrykiselev** [comment]
Matt, sorry for a long pause between messages :)

All documentation styles based on one of the older version of Foundation front-end framework.
Colors of alerts messages was chosen by creators of the framework.

Colors in version that used in capistrano docs looks like this (image from docs):


In up-to-date version of framework colors was changed and looks like:


I think so best (simply and clearly) solution is to update colors, remove border and set text color to black and font-weight to normal by default. Updated version of the alerts looks more subtle and not overbearing. :)

What do you think about it? :)

**Comment by leehambley** [comment]
> I think so best (simply and clearly) solution is to update colors, remove border and set text color to black and font-weight to normal by default. Updated version of the alerts looks more subtle and not overbearing. :)

Sounds good, I was 99% likely responsible for those decisions, they look must neater now.

**Comment by mattbrictson** [comment]
Looks great. Thanks again for your contribution! 🙇

**Comment by leehambley** [comment]
chic, thank you ! 👍 

screenshot 2017-02-24 17 50 59

**Comment by harrykiselev** [comment]
@mattbrictson, @leehambley I am very glad that you liked, thank you! :)

**Pull request merged**
