### PR TITLE
Fix space in git suffix. Fixes 1738

### PR DESCRIPTION
**Pull request by will-in-wi**
Fix for https://github.com/capistrano/capistrano/issues/1738

Still trying to figure out a test.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR! Testing might be too difficult to accomplish given the current codebase. Feel free to skip the test this time around. It will be easier to add a test once #1572 is merged.

If you could add a changelog entry I will merge this in.

**Comment by mattbrictson** [comment]
Although perhaps `gsub(/\s+/, " ")` would be better since it would catch all sorts of white space?

**Comment by will-in-wi** [comment]
I added the changelog entry and swapped `#tr` for `#gsub`.

**Comment by mattbrictson** [comment]
Looks good. Thanks! ✨

**Pull request merged**
