### PR TITLE
added check to stop printing parenthesis if the default is `nil`

### PR DESCRIPTION
**Pull request by chamini2**
Fix for #1834 

Was planning on writing tests, but I don't really understand what's happening at [question_spec.rb](https://github.com/capistrano/capistrano/blob/bf45cbafe5ef396933c81f334bdbc8c6d32a38c2/spec/lib/capistrano/configuration/question_spec.rb).

### Short checklist

- [x] Did you run `bundle exec rubocop -a` to fix linter issues?
- [ ] If relevant, did you create a test?
- [x] Did you confirm that the RSpec tests pass?
- [x] If you are fixing a bug or introducing a new feature, did you add a CHANGELOG entry?

### CODE REVIEW

**Comment by mattbrictson** [comment]
Looks like the new version of RuboCop is unhappy. I'll investigate.

**Comment by mattbrictson** [comment]
@chamini2 Can you please rebase on top of the latest `master`? That should clear up the RuboCop errors. Thanks for the PR!

**Comment by chamini2** [comment]
Done, @mattbrictson, something else that needs to get done?

**Comment by mattbrictson** [comment]
Thanks! Could you also add a simple test for the no-default case? There are existing specs in `question_spec.rb` that you should be able to amend. Otherwise it looks good. 👍

**Comment by chamini2** [comment]
@mattbrictson, added tests and rebased from `master`. I think it should be ready now? Let me know!

**Comment by mattbrictson** [comment]
@chamini2 It looks like @capistrano-bot is [still upset](https://github.com/capistrano/capistrano/pull/1835#issuecomment-273972646). Can you put back the `* Your contribution here!` line that you removed?

Once that it is green I'll merge the PR. Thanks!

**Comment by chamini2** [comment]
Done! @mattbrictson

**Comment by mattbrictson** [comment]
🙌 Thanks

**Pull request merged**
