### PR TITLE
Added BC support for rake < 11. Resolves #1740

### LINKED ISSUE #1740: Capistrano 3.6.0 breaks when used with Rake < 11.0.0, despite gemspec that allows it
#### Steps to reproduce

1. Have rake version '>= 10.0.0' and '< 11..0.0' installed either via dependencies or specified in Gemfile
2. Install Capistrano
3. bundle exec cap -T --trace

#### Expected behaviour
Should show available capistrano tasks

#### Actual behaviour
```shellsession
cap aborted!
NoMethodError: undefined method `already_invoked' for <Rake::Task load:defaults => []>:Rake::Task
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/dsl.rb:16:in `invoke'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/application.rb:91:in `load_imports'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:697:in `raw_load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/application.rb:14:in `run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/bin/cap:3:in `<top (required)>'
bin/cap:17:in `load'
bin/cap:17:in `<main>'
```

looking at line 16 of capistrano-3.6.0/lib/capistrano/dsl.rb reveals
```ruby
      if task && task.already_invoked
```
Digging around the rake github repo reveals that Rake::Task#already_invoked is available only in 11.0.0, capistrano.gemspec specifies:
```ruby
  gem.add_dependency "rake", ">= 10.0.0"
```

#### Your configuration
Gemfile contains
```ruby
gem 'rake', '~> 10.5.0'
gem 'capistrano'
```
Paste Capistrano's `doctor` output here (`cap <stage> doctor`):
```shellsession
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `already_invoked' for <Rake::Task load:defaults => []>:Rake::Task

Tasks: TOP => staging
(See full trace by running task with --trace)
```

#### Workaround
Until gemspec/method is fixed, place rake in Gemfile with version above 11.0.0.
```ruby
gem 'rake',  '~> 11.2.2'
```

### PR DESCRIPTION
**Pull request by troelskn**

### CODE REVIEW

**Comment by troelskn** [comment]
No tests, since this is a third-party issue. I ran tests locally with rake `10.5.0` to verify the issue, then patched and ran tests again, where they passed.

**Comment by mattbrictson** [comment]
Thanks for this! It seems to do the trick. Can you include a changelog entry to the effect of "restores compatibility with Rake 10.x" and reference #1740?

**Comment by troelskn** [comment]
@mattbrictson done

**Comment by mattbrictson** [comment]
I'm not seeing the changelog edit in your latest commit. Can you double-check you pushed your latest changes? Thanks.

**Comment by troelskn** [comment]
You're right - didn't push it after all. Here you go.

**Comment by mattbrictson** [comment]
Oops, there is now a conflict preventing me from merging this PR. Looks like it is because you removed the "your contribution here" line from the changelog. Can you resolve the conflicts, please?

**Comment by mattbrictson** [comment]
@troelskn I'd love to merge this PR so that we can release a new version of Capistrano with this Rake fix. Can you resolve the conflicts when you have a chance so that I can do the merge? Thanks!

**Comment by mattbrictson** [comment]
Thanks! Merging.

**Pull request merged**
