### PR TITLE
[CI] Test against Ruby 2.5

### PR DESCRIPTION
**Pull request by nicolasleger**
### Summary

CI against latest Ruby 2.5

### Short checklist

- [x] Did you run `bundle exec rubocop -a` to fix linter issues?
- [x] If relevant, did you create a test?
- [x] Did you confirm that the RSpec tests pass?
- [ ] If you are fixing a bug or introducing a new feature, did you add a CHANGELOG entry?

### Other Information

https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/

### CODE REVIEW

**Comment by nicolasleger** [comment]
The failing test is the the same as the current master branch.
Might restart failing jobs.

**Comment by mattbrictson** [comment]
Thanks for the PR! I'll open a separate issue for the master build failure.

**Comment by mattbrictson** [comment]
A bunch of new rubies where released yesterday, including 2.5.1. Could you update the PR to use those instead? Thanks!

**Comment by nicolasleger** [comment]
Updated

**Comment by mattbrictson** [comment]
Thanks! Once #1975 is merged I will merge this in as well.

**Comment by olleolleolle** [comment]
@leehambley I believe `master` now tests Ruby 2.5, so the goals here have been met. 🎉

**Pull request closed without merging**
