### PR TITLE
Adding shallow clone feature to cap 3

### PR DESCRIPTION
**Pull request by pwaterz**

### CODE REVIEW

**Comment by leehambley** [comment]
How about tests and checking the CONTRIBUTION notes, sorry as it stands I can't merge this (I know it's frustrating for such a simple change to have to jump through hoops, but after your contribution we have to maintain the code until the end of time!)

**Comment by geshan** [comment]
+1 

fixing tests would be great.

**Comment by pwaterz** [comment]
I will update this when I get some time.

**Comment by leehambley** [comment]
Sorry @pwaterz the tests all failed as a result of this, could you take another look please? https://travis-ci.org/capistrano/capistrano/builds/69349041

**Comment by pwaterz** [comment]
I have cleaned up the code, looks like someone else already merged some code into master though.

**Comment by pwaterz** [comment]
Opened a new pull request to clean some things up https://github.com/capistrano/capistrano/pull/1476

**Pull request closed without merging**
