### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by leehambley** [comment]
@mattbrictson my view on this is that we already use Rubocop and I'm not too interested in yet-another-badge for the README, the CodersClan one we tried in the past brought close to zero value, I'm a bit skeptical of introducing new ones.

@korzonek I mean no disrespect, I'm also a SaaS founder, but I'm not sure it's suitable for us right now.

**Comment by mattbrictson** [comment]
We already have a Code Climate badge, which on the surface seems very similar. I'd be willing to switch it out for codebeat if it is a compelling upgrade. @korzonek what are the advantages of using codebeat vs Code Climate?

**Comment by korzonek** [comment]
There are a few things that are not available in code climate and you can find in codebeat.

* _Multi-Language support for mobile and web applications_. We implemented all algorithms on our own. It means relatively quickly we can support more languages both for mobile and web. At this stage we analyse **Swift, Ruby, Python** and **Go**.
* _Quick Wins_. After analysing your project we will suggest you issues in code with the biggest overall impact on your project's health. Try to refactor these hot spots first and see how your GPA improves.
* _Compare Changes_. In the stream of Recent Changes you will be able see what exactly caused your classes to improve or degrade.

We are also about to release nice support for pull requests in codebeat.

Please check [our documentation](https://help.codebeat.co/docs) to learn how we are different and how we do what we do :)

We launched in January and it would be fantastic if you could share with us feedback and things you would like to see in this type of tool. It will help us to prioritise things in our backlog. 

It will make us all very happy :)

Giphy

**Comment by leehambley** [comment]
Sorry, I've reached badged service overload after being bombarded by coveralls.io *comments* on a merged PR. I don't know why they don't use build statuses like everyone else, but it's a bridge too far. Sorry @korzonek - good luck with codebeat.

**Comment by korzonek** [comment]
@leehambley I can fully understand your point of view at the same time we don't add _comments_ so there won't be too much noise around :)

Well... please give a try to codebeat. I hope you will like it. We are also about to release nice support for pull requests.

**Comment by leehambley** [comment]
@korzonek feel free to ping me back in a couple of months. Appreciate that you're using the right APIs when you launch that, but for now it's a no - but founder to founder, please come back to me in the nearish future.

**Comment by korzonek** [comment]
@leehambley Super! I'll get in touch in 2 months time :)

**Pull request closed without merging**
