### PR TITLE
Restricting the uploaded git wrapper file permissions to 700.

### LINKED ISSUE #910: Files in tmp should be created with 0600, and any created directories with 0700.
Ignoring the fact that this breaks some of the group related policies on which I personally rely, the file modes of incidentally created files and directories by Capistrano are too open, and may present a security risk under certain circumstances.

### PR DESCRIPTION
**Pull request by irvingwashington**
Additional step in the 'Creating the repo' scenario to test this adjustment.

Fixes #910

### CODE REVIEW

**Comment by leehambley** [comment]
Do you not want this improvement to be attributed to you?

**Comment by irvingwashington** [comment]
I'm quite new to OSS, so I'm not sure if I should add every tiny bugfix to the changelog.
It's ok to merge this as commited.

**Comment by mattbrictson** [comment]
You are on a roll with these contributions. Thanks again, @irvingwashington!

A couple quick notes:

* You don't have to give yourself credit, but please mention the bug fix in the CHANGELOG. It is appreciated for all user-facing bug fixes, even small ones.
* Please mention the issue number (#910 in this case) in the body of your GitHub PR description, not the title. Placing the issue number in the description allows GitHub to automatically link up the issue and PR, which helps the project maintainers.

**Comment by mattbrictson** [comment]
Specifically, write this in the PR body on its own line: `Fixes #910`. That way, when the PR is merged, GitHub will automatically close issue #910 at the same time.

**Comment by irvingwashington** [comment]
Thanks for those hints and helping me out in general, I've applied the changes to the PR.

**Pull request merged**
