### PR TITLE
Enable CommandLiteral cop

### PR DESCRIPTION
**Pull request by will-in-wi**
For discussion.

Followup to https://github.com/capistrano/capistrano/pull/1594

### CODE REVIEW

**Comment by mattbrictson** [comment]
Yes, I much prefer the standard backticks. :+1:

**Comment by leehambley** [comment]
Are we merging all of these individually, and @will-in-wi is whack-a-mole'ing conflicts between PRs that interfere with eachother ?

**Comment by mattbrictson** [comment]
Well, the PRs say "for discussion", so maybe once discussion has finished @will-in-wi can roll them approved ones into a single commit.

**Comment by will-in-wi** [comment]
I was planning on the whack-a-mole approach. However, I'm more than happy to take the approved PRs, merge them into one giant, squashed one, and submit it as a new PR.

Whichever you prefer.

**Comment by will-in-wi** [comment]
"For discussion" was intended to mean that it wouldn't bother me if a PR were rejected. This is just to make it easier to make decisions.

**Comment by mattbrictson** [comment]
Whichever is less work for you, @will-in-wi.

**Comment by will-in-wi** [comment]
I think it will be easier for me to keep track of whack-a-mole, if you guys don't mind. I just need some sort of official approval on each PR, and I'll rebase and clear it for merge.

**Pull request merged**
