### PR TITLE
Issue #1710 remove remote_file method

### PR DESCRIPTION
**Pull request by SaiVardhan**
#1710  remove remote_file method

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for doing this!

I am going to hold off merging this for the time being, because I would like to release 3.6.1 first with bug fixes only, and this would be a breaking change.

In the meantime, can you add a changelog entry noting that `remote_file` has been removed?

**Comment by SaiVardhan** [comment]
@mattbrictson 

Can you guide me how to add changelog entry.
 I am not pretty sure on that.

**Comment by mattbrictson** [comment]
> Can you guide me how to add changelog entry.

Sure! In `CHANGELOG.md` where it has this line:

```
* Your contribution here!
```

Just add another bullet below that line with a sentence describing your change, and credit yourself if you want to, like this:

```
* Your contribution here!
* `remote_file` feature has been removed and is no longer available to use @SaiVardhan
```

Please don't add a new version number section (e.g. `3.7.0`). Put your message under the existing `master` section. (The maintainers will add the appropriate version number when it comes time to publish the next release.)

Thanks!

**Comment by SaiVardhan** [comment]
Sure @mattbrictson will update the changes

**Comment by mattbrictson** [comment]
Thank you! Can you please rebase and fix the merge conflicts?

**Comment by mattbrictson** [comment]
3.6.1 was released earlier this week, so I think it is safe to merge this now. Thanks for your help! 🙇

**Pull request merged**
