### PR TITLE
Added options to set username and password when using Subversion as SCM

### PR DESCRIPTION
**Pull request by dsthode**
Add :svn_username and/or :svn_password to the deplyment file if Subversion needs authentication

### CODE REVIEW

**Comment by leehambley** [comment]
Thanks for this, I don't use SVN, haven't touched it for about 6/7 years, so I'll get around to testing it sooner or later, I have to check this doesn't break any of our test suite (which travis can't/won't run)

**Comment by dsthode** [comment]
Have had a look at the tests and noticed the SVN test suite was failing because of the new arguments passed to the functions. I have fixed the test suite and now all the SVN tests pass.

**Comment by leehambley** [comment]
Thanks @dsthode

**Comment by leehambley** [comment]
So the last thing is to point you at the CONTRIBUTING file, especially the part where you add yourself to the CHANGELOG so that you are credited in the way you prefer.

**Comment by dsthode** [comment]
Hi @leehambley already did add myself to the CHANGELOG file, thanks!

**Comment by leehambley** [comment]
Sorry missed that in your commits - my mistake!

**Comment by marcovtwout** [comment]
@leehambley I'm a bit surprised to see this patch hasn't made its way into a stable release yet. I'll use master for now, but when is a new release of v3 planned?

**Comment by leehambley** [comment]
I have no way to test a lot of the new stuff, so I've been stalling. Let me
know how master works for you!

**Comment by marcovtwout** [comment]
Using master and putting `svn_username` and `svn_password` works as expected.

Additional question: can I also pass these as arguments when running `cap deploy`?

**Comment by leehambley** [comment]
Read them from ENV in your setup script ?

**Comment by matatirosolutions** [comment]
@leehambley I can also confirm that this both resolves the issue of needing to supply credentials for Subversion.

**Comment by leehambley** [comment]
:+1:

**Comment by marcovtwout** [comment]
@leehambley Have you planned a release date yet? What other stuff do you need to test?

**Comment by leehambley** [comment]
No planned release date, no time to do a real test of any kind. Sorry, watch this space.

**Pull request merged**
