### PR TITLE
Modern solution to fix "Host key verification failed" error

### PR DESCRIPTION
**Pull request by kanmeiban**
The original proposed solution is cumbersome if you manage many servers or dynamically create and destroy virtual machines in the cloud.

### CODE REVIEW

**Comment by mattbrictson** [comment]
@kanmeiban thanks for the PR! Before I merge this, I'd like to understand how this solution works.

My understanding is that Capistrano already executes `git:check` early in the deploy process, well before any git commands are executed. See output below:

```
$ cap --dry-run --trace production deploy
** Execute production
** Execute load:defaults
** Execute deploy
** Execute deploy:starting
** Execute git:wrapper
** Execute git:check  <-------------------------
** Execute deploy:check
** Execute deploy:check:directories
** Execute deploy:check:linked_dirs
** Execute deploy:check:make_linked_dirs
** Execute deploy:check:linked_files
** Execute deploy:set_previous_revision
** Execute deploy:started
** Execute deploy:new_release_path
** Execute git:clone
** Execute git:update
** Execute git:create_release
** Execute deploy:updating
** Execute git:set_current_revision
** Execute deploy:set_current_revision
** Execute deploy:symlink:shared
** Execute deploy:symlink:linked_files
** Execute deploy:symlink:linked_dirs
** Execute deploy:updated
** Execute deploy:publishing
** Execute deploy:symlink:release
** Execute deploy:published
** Execute deploy:finishing
** Execute deploy:cleanup
** Execute deploy:finished
** Execute deploy:log_revision
```

Why would running `cap production git:check` be needed if `deploy` already runs `git:check` implicitly?

**Comment by kanmeiban** [comment]
@mattbrictson You're completely right, and on the morning after submitting this PR I realized `deploy:check` is run on every deploy. However I still cannot understand how running `cap deploy:setup` which invokes `git:check` helped me save the unknown github.com key. Here is my capistrano log:
```  
INFO ---------------------------------------------------------------------------
  INFO START 2023-10-28 20:59:56 +0300 cap staging deploy
  INFO ---------------------------------------------------------------------------
 DEBUG [6102ab7d] Running [ -d /home/pesho/www/staging/shared/generated/.git ] as pesho@do-pesho-infra-web
 DEBUG [6102ab7d] Command: [ -d /home/pesho/www/staging/shared/generated/.git ]
 DEBUG [f647f60c] Running [ -d /home/pesho/www/staging/shared/generated/.git ] as pesho@do-pesho-infra-db
 DEBUG [f647f60c] Command: [ -d /home/pesho/www/staging/shared/generated/.git ]
 DEBUG [ec5de57d] Running [ -d /home/pesho/www/staging/shared/generated/.git ] as pesho@do-pesho-infra-app
 DEBUG [ec5de57d] Command: [ -d /home/pesho/www/staging/shared/generated/.git ]
 DEBUG [6102ab7d] Finished in 1.180 seconds with exit status 0 (successful).
 DEBUG [f647f60c] Finished in 1.255 seconds with exit status 0 (successful).
 DEBUG [ec5de57d] Finished in 1.401 seconds with exit status 1 (failed).
  INFO [59854e55] Running /usr/bin/env git clone git@github.com:patuf/pesho_generated.git /home/pesho/www/staging/shared/generated as pesho@do-pesho-infra-app
 DEBUG [59854e55] Command: /usr/bin/env git clone git@github.com:patuf/pesho_generated.git /home/pesho/www/staging/shared/generated
 DEBUG [59854e55]       Cloning into '/home/pesho/www/staging/shared/generated'...
 DEBUG [59854e55]       ^MThe authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
  INFO ---------------------------------------------------------------------------
  INFO START 2023-10-28 22:25:19 +0300 cap staging deploy:setup
  INFO ---------------------------------------------------------------------------
  INFO ---------------------------------------------------------------------------
  INFO START 2023-10-28 22:28:16 +0300 cap staging git:check
  INFO ---------------------------------------------------------------------------
  INFO [a00357a1] Running /usr/bin/env mkdir -p /tmp as pesho@do-pesho-infra-web
 DEBUG [a00357a1] Command: /usr/bin/env mkdir -p /tmp
  INFO [c0127552] Running /usr/bin/env mkdir -p /tmp as pesho@do-pesho-infra-app
 DEBUG [c0127552] Command: /usr/bin/env mkdir -p /tmp
  INFO [e598b131] Running /usr/bin/env mkdir -p /tmp as pesho@do-pesho-infra-db
 DEBUG [e598b131] Command: /usr/bin/env mkdir -p /tmp
  INFO [e598b131] Finished in 1.853 seconds with exit status 0 (successful).
  INFO [a00357a1] Finished in 1.854 seconds with exit status 0 (successful).
  INFO [c0127552] Finished in 1.997 seconds with exit status 0 (successful).
 DEBUG Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 0.0%
 DEBUG Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 0.0%
  INFO Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 100.0%
  INFO Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 100.0%
 DEBUG Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 0.0%
  INFO [270024a5] Running /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh as pesho@do-pesho-infra-web
 DEBUG [270024a5] Command: /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh
  INFO [ed3bb621] Running /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh as pesho@do-pesho-infra-db
 DEBUG [ed3bb621] Command: /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh
  INFO Uploading /tmp/git-ssh-2a1467d69b291d56df8e.sh 100.0%
  INFO [01a2b571] Running /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh as pesho@do-pesho-infra-app
 DEBUG [01a2b571] Command: /usr/bin/env chmod 700 /tmp/git-ssh-2a1467d69b291d56df8e.sh
  INFO [270024a5] Finished in 0.256 seconds with exit status 0 (successful).
  INFO [ed3bb621] Finished in 0.330 seconds with exit status 0 (successful).
  INFO [01a2b571] Finished in 0.198 seconds with exit status 0 (successful).
  INFO [92088f9d] Running /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD as pesho@do-pesho-infra-db
  INFO [638cf974] Running /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD as pesho@do-pesho-infra-app
 DEBUG [92088f9d] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-2a1467d69b291d56df8e.sh" ; /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD )
 DEBUG [638cf974] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-2a1467d69b291d56df8e.sh" ; /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD )
  INFO [52ca34bc] Running /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD as pesho@do-pesho-infra-web
 DEBUG [52ca34bc] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-2a1467d69b291d56df8e.sh" ; /usr/bin/env git ls-remote git@github.com:patuf/pesho.git HEAD )
 DEBUG [638cf974]       Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
```

**Comment by mattbrictson** [comment]
@kanmeiban Hmm. There are some aspects of the log output that aren't familiar to me. Specifically, this command:

```
[ -d /home/pesho/www/staging/shared/generated/.git ]
```

To my knowledge, the standard Capistrano git implementation does not use `-d`. It uses `-f`:

https://github.com/capistrano/capistrano/blob/35dda25423ee6cd8b97fa3dc176c7f2688363686/lib/capistrano/scm/git.rb#L36

I wonder, are you using any custom or third-party Capistrano plugins that might be altering Capistrano's git behavior, or registering hooks that run at the start of the deploy before `git:check`?

**Comment by kanmeiban** [comment]
> I wonder, are you using any custom or third-party Capistrano plugins that might be altering Capistrano's git behavior, or registering hooks that run at the start of the deploy before `git:check`?

This is a custom cap task that clones am additional repo, not the main app repo. It seems running `git:check` explicitly stores the changed SSH key, while the custom task cannot do it alone. This is something specific to my setup. 

Please, accept my apologies for wasting your time. Thank you very much for your comment that helped me track the culprit for this behavior. I am closing this now.

**Pull request closed without merging**
