### PR TITLE
Add dkdeploy to documentation of 3rd party plugins

### PR DESCRIPTION
**Pull request by bauschan**
### Summary

Adds the dkdeploy-core, dkdeploy-php and dkdeploy-typo3-cms gems to the 3rd party plugins section of the documentation

### CODE REVIEW

**Comment by leehambley** [comment]
What's dkdeploy, and what does it do? The docs just say "advanced capistrano tasks"

**Comment by bauschan** [comment]
Sorry, missed the link to the [documentation](https://dkdeploy.github.io/).

There's also an blog-post '[First steps with dkdeploy-typo3-cms](http://blog.dkd.de/first-steps-with-dkdeploy-typo3-cms/)' summarizing the steps to develop a [TYPO3 CMS](https://typo3.org/) Introduction package.

**Comment by leehambley** [comment]
Thanks, probably it makes sense to separate these into a separate list of PHP specific things, right ?

**Comment by bauschan** [comment]
Hmh, yes and no, [dkdeploy-core](https://github.com/dkdeploy/dkdeploy-core) isn't bound to PHP. We use it for deploying all kinds of web apps, typically Rails projects.
While [dkdeploy-php](https://github.com/dkdeploy/dkdeploy-php) and [dkdeploy-typo3-cms](https://github.com/dkdeploy/dkdeploy-typo3-cms) sit on top of [dkdeploy-core](https://github.com/dkdeploy/dkdeploy-core) and rely on an PHP environment for deployment.

**Comment by mattbrictson** [comment]
I'm willing to merge this as-is, if you can rebase it on `master`.

@leehambley any reservations?

**Comment by bauschan** [comment]
Rebase done. Thanx for taking care.

**Comment by leehambley** [comment]
None, just some UX concerns about the list on the site, but not enough to
block it.

**Comment by mattbrictson** [comment]
Hmm, GitHub is showing an odd-looking diff, but I will squash the commits down and it should be OK. Thanks for the PR!

**Pull request merged**
