### PR TITLE
Make add_role O(hosts) & fix port handling

### PR DESCRIPTION
**Pull request by dbenamy**
### Summary

This makes add_role O(hosts) instead of O(hosts^2). I'm using cap in a deployment with enough servers that the previous behavior makes it take 7+ seconds to start.

I also think I fixed a bug in add_host's handling of ports, but I'm not totally sure of the intended behavior so let me know if I misunderstood!

Each commit stands alone if that helps with reviewing.

### Other Information

I benchmarked using

```
from subprocess import check_output
from time import time

for cnt in range(0, 12001, 100):
    with file('Capfile', 'w') as f:
        f.write("require 'capistrano/setup'\n")
        f.write("role :r, %%w(%s)\n" % ' '.join(['i-%017d' % i for i in range(cnt)]))
    start = time()
    check_output(['bin/cap', '--rakefile=Capfile', '-T'])
    print '%d,%f' % (cnt, time() - start)
```

`RUBYLIB=lib python bench.py`

screen shot 2017-02-12 at 1 23 50 am

The detailed data is at https://docs.google.com/spreadsheets/d/14OvbOwF8eGflgWhYleI9RDkpmfUtDQDF-iH2oEIFPko. The commits shown there don't match the PR any more because I squashed in a tiny fix. They should be equivalent to 5aea6dc for baseline, and 45e1920 for the fix.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR and the detailed supporting data!

I may not have time to review the code in detail right away, but in the meantime I am curious to learn more about the potential breaking change. Does your change perhaps overlap with the breaking changes proposed in #1427?

**Comment by mattbrictson** [comment]
@leehambley or @will-in-wi could you take the lead on reviewing this one?

**Comment by leehambley** [comment]
Thanks for the PR @dbenamy , doubly so for including some plots about performance, it's a rare luxury in our position as maintainers to receive such things!

I'd love to know (just for fun) *what* exactly you're doing that warrants caring about the big-O complexity of some mundane part of setting up the roles, I might ping you off-list, whatever you're doing, sounds like a serious case!

As best [I can see](https://github.com/capistrano/capistrano/pull/1846/files#diff-0d9345682ea186c858c7b2c5f1fbceb9R68) we're still not considering the username as part of the host definition. 

Honestly, having re-read #1427 I can see both cases being valid, but we do just have to decide one. I consider #1427 to be somewhat moot since someone can commit a `./ssh/config` file with usernames and use descriptive hostnames, which is how I personally use Cap, but that doesn't need to affect this PR. Concretely: I think it's ok for a "server" to be the combo of hostname/ip and port.

I see that you changed [the spec](https://github.com/dbenamy/capistrano/blob/629e26284cb50b4980dc9d2a145cd457d3ea77bc/spec/lib/capistrano/configuration/servers_spec.rb#L131-L140) for how we treat usernames and ports in relation to hostnames, I believe this is the "potential breaking change" that @mattbrictson is talking about:

``` ruby
        it "can accept multiple servers with the same hostname but different ports or users" do
          servers.add_host("1", roles: [:app, "web"], test: :value, port: 12)
          expect(servers.count).to eq(2)
          servers.add_host("1", roles: [:app, "web"], test: :value, port: 34)
          servers.add_host("1", roles: [:app, "web"], test: :value, user: "root")
          servers.add_host("1", roles: [:app, "web"], test: :value, user: "deployer")
          servers.add_host("1", roles: [:app, "web"], test: :value, user: "root", port: 34)
          servers.add_host("1", roles: [:app, "web"], test: :value, user: "deployer", port: 34)
          servers.add_host("1", roles: [:app, "web"], test: :value, user: "deployer", port: 56)
          expect(servers.count).to eq(4)
        end
```

I always struggle parsing such banal code, but I suspect what you're expecting is the following status at the end of this block:

```
#<Capistrano::Configuration::Server:0x007fccbb6af8a8 @keys=[], @local=false, @user="deployer", @hostname="1", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007fccbb6af3f8 @properties={:test=>:value}, @roles=#<Set: {:app, :web}>>>
#<Capistrano::Configuration::Server:0x007fccbb6aeef8 @keys=[], @local=false, @user=nil,        @hostname="1", @port=12,  @properties=#<Capistrano::Configuration::Server::Properties:0x007fccbb6aeac0 @properties={:test=>:value}, @roles=#<Set: {:app, :web}>>>
#<Capistrano::Configuration::Server:0x007fccbb6ae480 @keys=[], @local=false, @user="deployer", @hostname="1", @port=34,  @properties=#<Capistrano::Configuration::Server::Properties:0x007fccbb6ae048 @properties={:test=>:value}, @roles=#<Set: {:app, :web}>>>
#<Capistrano::Configuration::Server:0x007fccbe07b4e8 @keys=[], @local=false, @user="deployer", @hostname="1", @port=56,  @properties=#<Capistrano::Configuration::Server::Properties:0x007fccbe07b088 @properties={:test=>:value}, @roles=#<Set: {:app, :web}>>>
```

According to these things we've got four server, all with the same hostname, but with different ports, I could live with that as a small change in the docu, and clean up the examples above and explain how it works, and why, and how the "workaround" should be employed?

**Comment by dbenamy** [comment]
Thanks for taking a look!

I hadn't seen https://github.com/capistrano/capistrano/issues/1427 before. I didn't go into this looking to change any behavior; I just noticed while working on it that there was an inconsistency in some cases where adding a server with the port specified using the properties hash updates a server
```
servers.add_host('host1')
=> [#<Capistrano::Configuration::Server:0x007f95130d1e98 @keys=[], @local=false, @user=nil, @hostname="host1", @port=nil>]
servers.add_host('host1', port: 1234)
=> #<Capistrano::Configuration::Server:0x007f95130d1e98 @keys=[], @local=false, @user=nil, @hostname="host1", @port=1234>
```
while adding it with the port specified in the host string creates a second
```
servers.add_host('host1')
=> [#<Capistrano::Configuration::Server:0x007f81c51f2860 @keys=[], @local=false, @user=nil, @hostname="host1", @port=nil>]
servers.add_host('host1:1234')
=> [#<Capistrano::Configuration::Server:0x007f81c51f2860 @keys=[], @local=false, @user=nil, @hostname="host1", @port=nil>, #<Capistrano::Configuration::Server:0x007f81c51ca720 @keys=[], @local=false, @user=nil, @hostname="host1", @port=1234>]
```

I listed is as a potential breaking change in the CHANGELOG since it's possible that people are relying on the existing behavior.

> According to these things we've got four server, all with the same hostname, but with different ports, I could live with that as a small change in the docu, and clean up the examples above and explain how it works, and why, and how the "workaround" should be employed?

Cool. To be clear- I don't have a ton of time to get involved in what seems to be a very long running discussion about how the semantics should work. If this port handling fix is a clear win, I'm happy to update whatever needs updating, if you could point me at exactly what that is. If it makes accepting this PR any harder though, I can re-implement the previous behavior with the O(n) improvement. Just let me know!

> I'd love to know (just for fun) what exactly you're doing that warrants caring about the big-O complexity of some mundane part of setting up the roles, I might ping you off-list, whatever you're doing, sounds like a serious case!

I'm using cap in a deployment with enough servers that this is relevant! :-) There are maybe 30 roles, some with hundreds of hosts, and it takes 7 - 8 seconds for cap to start up before it does any actual tasks.

**Comment by leehambley** [comment]
> Cool. To be clear- I don't have a ton of time to get involved in what seems to be a very long running discussion about how the semantics should work.

Agreed!

I think we've done enough here. I'd take it on my plate to open another ticket to fix the documentation to explain how it is now, and provide some examples.

I want to avoid bikeshedding around some trivialities that you happened to fall over, when I don't think any of us truly feel like planting the proverbial flag and proclaiming the one true way to name or define servers.

Other maintainers, @mattbrictson and @will-in-wi any stake in this? First pass over the review LGTM although I had some weird local test failures that travis didn't reproduce, I think we're fine ?

**Comment by mattbrictson** [comment]
LGTM 👍
Feel free to merge, @leehambley

**Comment by dbenamy** [comment]
Thanks! Any idea when the next release will be?

**Comment by mattbrictson** [comment]
Capistrano is generally released every 6 weeks. So the next rubygems release will be around March 10th, give or take.

**Comment by dbenamy** [comment]
Excellent, thanks again!

**Pull request merged**
