### PR TITLE
Initial draft of version locking documentation

### PR DESCRIPTION
**Pull request by will-in-wi**
Documentation per https://github.com/capistrano/capistrano/issues/1929

### CODE REVIEW

**Comment by leehambley** [comment]
> Even today, it is easy to run Capistrano without `bundle exec` or a binstub (`bin/cap`, obtained through `bundle binstub capistrano`), resulting in unexpected behavior.

Reads really well barring the american english :trollface:  (just kidding, we standardi*z*ed on US english at some point I think)

If memory serves the version comparator comes from Rubygems - looks like we use https://ruby-doc.org/stdlib-2.4.2/libdoc/rubygems/rdoc/Gem/Dependency.html#method-i-3D-7E here https://github.com/capistrano/capistrano/blob/master/lib/capistrano/version_validator.rb#L16 - maybe we should link the docs, this version comparator works totally differently in Ruby for example from Node.js (which bites me once a week)

**Comment by will-in-wi** [comment]
We could go with mid-Atlantic English and try to have a 50/50 split of U.S. and U.K. English spellings. 😄

Heh, when I looked at the code, I just assumed that strings like `~> 3.0.9` were some magic type of Regex I'd never heard of. I'm kind of surprised that they overrode that operator… Either way, really good to know, I'll update the docs.

**Comment by will-in-wi** [comment]
I've pushed the clarification.

**Comment by leehambley** [comment]
LGTM

**Pull request merged**
