### PR TITLE
Cleaning up git shallow clone and adding tests

### PR DESCRIPTION
**Pull request by pwaterz**

### CODE REVIEW

**Comment by leehambley** [comment]
Thanks @pwaterz - it looks like your changes to the CHANGELOG were busted somehow - https://github.com/capistrano/capistrano/pull/1476/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by pwaterz** [comment]
Are you referring to the removed white space?

**Comment by leehambley** [comment]
Your entry into the Changelog appears *above* the heading for this release.

**Comment by pwaterz** [comment]
That better?

**Pull request merged**
