### PR TITLE
Use correct capistrano version in deploy.rb.erb

### PR DESCRIPTION
**Pull request by ojab**
Use actual capistrano version instead of hardcoded '3.1'.

### CODE REVIEW

**Comment by Kriechi** [comment]
Can we detect if the generator is called from a Bundler-environment?
If yes I would suggest only adding the version-lock in generator calls from non-bundler environments.

**Comment by jgrevich** [comment]
@Kriechi perhaps just checking for the prescence of a `Gemfile` or `Gemfile.lock

**Comment by Kriechi** [comment]
@jgrevich just looking for a `Gemfile` is probably a bad idea.
But to keep it simple I would be happy with just changing the comment to something like:


```ruby
# If you do not use Bundler to manage your Gem versions, 
# you can lock this Capistrano config to a specific version.
# lock '<%= Capistrano::VERSION %>'
```

Please note that the `lock` command is commented out by default, I think most of the people use Capistrano in a Bundler-env - so I would not want to bother these guys with version locking.

**Comment by jgrevich** [comment]
> Please note that the lock command is commented out by default, I think most of the people use Capistrano in a Bundler-env - so I would not want to bother these guys with version locking.

:+1:

**Comment by kirs** [comment]
Thanks for your PR.
This is already fixed in https://github.com/capistrano/capistrano/blob/master/lib/capistrano/templates/deploy.rb.erb#L1

**Pull request closed without merging**
