### PR TITLE
Make name of current directory configurable

### PR DESCRIPTION
**Pull request by websi**
Add configuration variable to define name of directory/symlink "current"

### CODE REVIEW

**Comment by mattbrictson** [comment]
What's your use case for changing the `current` name? Just curious.

**Comment by websi** [comment]
Some of our customers use a different directory structure for their Apache vhosts and they will not change this structure.
So we have to change the name of the "current" directory / symlink.
In this case, the name of the "current" directory / symlink is "htdocs".

**Comment by will-in-wi** [comment]
To throw in my 2¢, when I've run into this scenario, I manually make `htdocs` a symlink to `current`.

In my experience, such cases usually also have other constraints which make Capistrano a difficult sell, so deploying Capistrano to a different directory entirely, and symlinking to that directory, has worked better for me.

**Comment by mattbrictson** [comment]
I see. This seems like a fairly benign change that could make it easier/possible for some people to use Capistrano, so I'm willing to merge it.

But first, can you make the following edits?

1. Fix merge conflicts.
2. In your commit message, mention the "htdocs" scenario that motivated this change, just so that future contributors running `git blame`, etc. will understand what this feature is for.
3. In the CHANGELOG entry, mention the directory name can be overridden by setting `:current_directory`. As it stands the bullet point is a little vague.

Thanks!

**Comment by websi** [comment]
Updated the pull request

**Comment by mattbrictson** [comment]
Thanks! 🙌

**Pull request merged**
