### PR TITLE
Enable TrailingCommaInLiteral cop

### PR DESCRIPTION
**Pull request by will-in-wi**
For discussion.

Followup to https://github.com/capistrano/capistrano/pull/1594

### CODE REVIEW

**Comment by mattbrictson** [comment]
No strong opinion, so I guess let's go with RuboCop's default. :+1:

**Comment by mattbrictson** [comment]
@will-in-wi Can you fix this and other conflicts again? Sorry, due to merging this may take a few more rounds.

**Comment by will-in-wi** [comment]
All rebased. Waiting for tests to pass.

**Comment by mattbrictson** [comment]
Ignoring intermittent Rubinius segfault. :neutral_face:

**Pull request merged**
