### PR TITLE
Add capistrano-hanami to plugins list

### PR DESCRIPTION
**Pull request by mgrachev**

### CODE REVIEW

**Comment by leehambley** [comment]
Can you tell us what is hanami and how does it relate to Capistrano?

**Comment by mgrachev** [comment]
[Hanami](https://github.com/hanami/hanami) is a modern web framework for Ruby.

**Comment by mattbrictson** [comment]
LGTM 👍

**Comment by leehambley** [comment]
Same, let's merge it. I'm still not sure what Hanami is, bit fair enough!
We need to organize the plugins list eventually!

(Sent from my Nexus 6, please forgive typos!)

**Comment by mattbrictson** [comment]
Thanks for the PR! ✨

**Pull request merged**
