### PR TITLE
Use default Rubocop recommended syntax for string literals.

### PR DESCRIPTION
**Pull request by will-in-wi**
For discussion.

This changes the default syntax to single quotes unless there is string interpolation or apostrophes.

Followup to https://github.com/capistrano/capistrano/pull/1594

### CODE REVIEW

**Comment by mattbrictson** [comment]
I prefer double quotes, and I think the trend among open source is going in this direction. My unscientific survey of the popular Ruby projects on GitHub shows a preference for double-quotes. And FWIW, thoughtbot is on board as well: their HoundCI code style service defaults to double quotes.

**Comment by will-in-wi** [comment]
I think it will be easier for me to keep track of whack-a-mole, if you guys don't mind. I just need some sort of official approval on each PR, and I'll rebase and clear it for merge.

**Comment by will-in-wi** [comment]
I personally prefer single quotes. My argument for it is because it allows me at a glance to see whether a string is doing anything different like string interpolation.

With that said, this really is personal preference. It wouldn't bother me at all if Capistrano stuck with double-quotes.

**Comment by will-in-wi** [comment]
Okay, last one. I've rebased, but it sounds like this might be a close as wontfix.

Let's make a call one way or the other and close or merge. @leehambley ?

**Comment by will-in-wi** [comment]
Well, let's call that a decision. Closing.

Thanks for the discussion!

**Comment by leehambley** [comment]
Ohh, I was in favour of merge :) but no strong opinion.

**Comment by will-in-wi** [comment]
Heh. I don't care much. I go back and forth on this particular one. Let's stick with double-quotes.

**Pull request closed without merging**
