### PR TITLE
Moved the Official Plugins into a separated page.

### PR DESCRIPTION
**Pull request by InFog**
Also added information to expand the list of 3rd party plugins.

### CODE REVIEW

**Comment by InFog** [comment]
Actually missing some comments here. I think this way shows more clear which plugins are maintained officially.

Another small issue I had: It was not possible to use the dependencies on `Gemfile.lock`, so I had to update them (I guess due to old versions). Should I add this update to the merge request?

**Comment by mattbrictson** [comment]
This is a nice improvement, thanks!

Regarding the `docs/Gemfile.lock`: please submit a patch as a separate PR. Updates to the docs lock file can have unpredictable effects on the rendering of the site, so I'd like to give that a careful review.

**Comment by InFog** [comment]
Cool. Thank you, @mattbrictson!

I created the PR updating `Gemfile.lock` at #1923.

**Comment by InFog** [comment]
Btw, @mattbrictson anything else that bothers people on the docs? Since this is my second commit there I think I can do some more ;-)

**Comment by mattbrictson** [comment]
Hi @InFog, thanks for the offer! If you browse the [documentation](https://github.com/capistrano/capistrano/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) label you might find some other chores to work on. The ones I'd particularly like to see solved are #1884, #1870, #1763, and #1758. The last 2 are probably the easiest to fix.

Any help you can provide would be much appreciated! 🙇

**Comment by InFog** [comment]
Thanks, @mattbrictson. I will take a look on those.

**Pull request merged**
