### PR TITLE
Fixed bash command which tests for existence of manifest file.

### PR DESCRIPTION
**Pull request by vpuzzella**
Fixes https://github.com/capistrano/capistrano/issues/1702

### CODE REVIEW

**Comment by will-in-wi** [comment]
Are we still maintaining v2?

**Comment by mattbrictson** [comment]
I have no way of testing v2, so for me personally, I am not maintaining it. Unless the PR fixes a critical bug in a way that is obvious from looking at the diff and has no chance of unintended consequences. This PR doesn't qualify IMHO.

**Comment by leehambley** [comment]
I think I the patch makes sense, Bash won't expand a * in single quotes,
however I'm in favour of closing lest we send a signal that such small
issues qualify as "critical" for V2 releases.

**Comment by will-in-wi** [comment]
Can we say that officially we do not support v2? Then we close all v2 related tickets, and if someone really wants to maintain v2, they can fork it, or perhaps we could work with them. But right now, no maintainers use it, and I think 3 has been out long enough to fix most of the issues and encourage migration.

I'd be in favor of wholly unsupporting v2.

**Comment by mattbrictson** [comment]
I agree that v2 should be officially unsupported. Closing all v2 tickets seems severe, but it is probably the right thing to do, considering those issues will never be fixed.

*Unofficially,* we could make an exception to this rule in an extreme scenario. For example (very contrived): say a new version of Ruby or Bundler comes out and completely breaks v2, and the fix is a simple one-liner. I would hate to leave all v2 legacy users out in the cold just on principle.

**Comment by leehambley** [comment]
Agreed, let's formally EOL V2 with the next release of cap we can mention
it in the release notes?

**Comment by will-in-wi** [comment]
Here's one way of saying this in the CHANGELOG: https://github.com/capistrano/capistrano/pull/1932

**Comment by will-in-wi** [comment]
We've officially stopped support of Capistrano 2 and are not accepting patches for it any longer.

Thank you for your work on this! Sorry for the long wait and unsatisfying conclusion.

**Pull request closed without merging**
