### PR TITLE
Allow rbx-2 to fail without breaking Travis build

### PR DESCRIPTION
**Pull request by mattbrictson**
Addresses #1783 

> Maybe for the moment, make rubinius an allowed failure, and then leave this ticket open for a while for others to jump in.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Seems to work 👍 

screen shot 2016-10-03 at 11 45 22 am

**Comment by mattbrictson** [comment]
@will-in-wi LGTM?

**Comment by leehambley** [comment]
LGTM, does anyone really use rubinius?

(Sent from my Nexus 6, please forgive typos!)

**Comment by mattbrictson** [comment]
Thanks, merging!

**Pull request merged**
