### PR TITLE
Use git_wrapper_path when setting GIT_SSH

### PR DESCRIPTION
**Pull request by thickpaddy**
Apologies, this went missing when resolving merge conflicts for #1517 

@mattbrictson could you test this for me? Sorry, not using Capistrano at the moment, and don't have anything set up to test locally. Thanks.

### CODE REVIEW

**Comment by thickpaddy** [comment]
BTW I've dug out the original commit to confirm that this is all I missed, and it certainly seems to be. Should be good after this PR is merged, but apologies again for messing up all the same :-(

**Comment by mattbrictson** [comment]
Thanks for the quick turnaround! I must have tested it before the merge conflicts were resolved and failed to notice the regression.

I'm running the Cucumber suite now and will do a test deployment after that.

**Comment by mattbrictson** [comment]
Looks good. Thank you! 🙌

**Comment by thickpaddy** [comment]
Woot! Thanks for testing 👍

**Comment by leehambley** [comment]
Thank you both for a smooth fix 🚀

**Pull request merged**
