### PR TITLE
fix/role_filter greedy matching

### PR DESCRIPTION
**Pull request by cseeger-epages**
### Summary
fix for issue #1766 role_filter
added fix for exact matching role filter and spec tests

### Short checklist

[x] tested changes with bundle exec rake spec rubocop
[x ] tests created
[x ] tests work with fix and break without fix

### CODE REVIEW

**Comment by will-in-wi** [comment]
This looks good to me. @mattbrictson?

**Comment by mattbrictson** [comment]
Looks good. Thanks!

@cseeger-epages can you fix the merge conflict, please?

**Comment by will-in-wi** [comment]
@mattbrictson: Looks like the conflicts are fixed now.

**Comment by mattbrictson** [comment]
@cseeger-epages Thanks for fixing the conflicts. Could you also modify the CHANGELOG to mention this fix? E.g.

```diff
 * Your contribution here!
 * `remote_file` feature has been removed and is no longer available to use @SaiVardhan
-* fix bug with greedy matching in host_filter [#1766](https://github.com/capistrano/capistrano/issues/1766) (@cseeger-epages)
+* Fix bug where host_filter and role_filter were overly greedy [#1766](https://github.com/capistrano/capistrano/issues/1766) (@cseeger-epages)
```

**Comment by cseeger-epages** [comment]
sry forget to mention the role_filter

**Comment by mattbrictson** [comment]
Thanks! Merged

**Pull request merged**
