### PR TITLE
Add deploy:revisions_log

### PR DESCRIPTION
**Pull request by elia**
Show revisions log of the last 10 deploys.

Did a quick GitHub edit to start the discussion, will add specs and tune stuff if necessary.

cc @masterkain

### CODE REVIEW

**Comment by leehambley** [comment]
Do we really need an internal task for `cat`ing a file on the server?

**Comment by elia** [comment]
It's a `cat` (`tail`) on a server of a specific file in a specific path on a remote server to which you connect on some port with an identity file etc. …you got the idea ;)

I need it regularly, especially when pushing branches to staging servers. 
Doesn't seem out of place to me as it fits nicely under the definition of automation.
Also writing that file is part of the default deployment procedure and the filename is "owned" by capistrano itself.

That's all I got :)

**Comment by leehambley** [comment]
Closing because it doesn't meet the contribution guidelines.

**Comment by elia** [comment]
Does this mean that when will meet the contribution guidelines it will be merged?

I'm asking just to be sure this makes sense before trying to find the time to polish the PR.

**Comment by leehambley** [comment]
It seems like it'll be a lot of work to add tests and everything for this, and I don't just know if it's worth it, it's only a one-liner, plus the boiler plate code, don't feel obliged to work on the PR, but if you can get it tested (which I suspect will be difficult) I'd be happy enough to merge it.

**Pull request closed without merging**
